FROM alpine:edge

# install node
RUN apk add --no-cache nodejs-npm tini

# set working directory
WORKDIR /root/demochat

# copy project file
COPY package.json .

# set NODE_ENV to dev
ENV NODE_ENV dev

# install node packages
RUN apk add --no-cache --virtual .build-dep python make g++ krb5-dev && \
    npm set progress=false && \
    npm config set depth 0 && \
    npm install && \
    npm cache clean && \
    apk del .build-dep && \
    rm -rf /tmp/*

# copy app files
COPY . .

# Set tini as entrypoint
ENTRYPOINT ["/sbin/tini", "--"]

CMD npm run migrate && npm run test
